### ISSUE TITLE
i tried to use for pnpm but im getting an error with purl

### ISSUE THREAD

**Issue by augustobritodev** [jhutchings1/spdx-to-dependency-graph-action#33]
![image](https://user-images.githubusercontent.com/7965922/203630279-dfea3fe4-93c2-46eb-a38e-f413ba3baab2.png)

**Comment by jhutchings1** [comment]
@augustobritodev Do you have a pnpm-lock.json that reproduces the error? I haven't been able to reproduce with my test repository.
