### ISSUE TITLE
Action broken for Alpine using Syft `v0.66.0`

### ISSUE THREAD

**Issue by stevehipwell** [jhutchings1/spdx-to-dependency-graph-action#44]
When using this action on SBOMs with Alpine packages generated by Syft `v0.66.0` or later I get the following error. This error seems to be caused by a change to the purl. For reference it looks like the change is [valid](https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst#apk) but I'm not sure if it's the action code or GitHub which has the issue?

> Error: HTTP Status 422 for request POST https://api.github.com/repos/***/fluentd-aggregator/dependency-graph/snapshots
Error: Response body:
{
  "message": "invalid package url: in manifest '***/fluentd-aggregator@sha256:b5c705b81e919a83fb6f246d6cdeebe4d67771dbcfb7cdac8eb223a849a104df' decoding 'pkg:apk/alpine/tini@0.19.0-r1?arch=x86_64&distro=alpine-3.17.1&upstream=tini': invalid package url type: apk",
  "documentation_url": "https://docs.github.com/rest/reference/dependency-graph#create-a-snapshot-of-dependencies-for-a-repository"
}
Error: invalid package url: in manifest '***/fluentd-aggregator@sha256:b5c705b81e919a83fb6f246d6cdeebe4d67771dbcfb7cdac8eb223a849a104df' decoding 'pkg:apk/alpine/tini@0.19.0-r1?arch=x86_64&distro=alpine-3.17.1&upstream=tini': invalid package url type: apk
Error: HttpError: invalid package url: in manifest '***/fluentd-aggregator@sha256:b5c705b81e919a83fb6f246d6cdeebe4d67771dbcfb7cdac8eb223a849a104df' decoding 'pkg:apk/alpine/tini@0.19.0-r1?arch=x86_64&distro=alpine-3.17.1&upstream=tini': invalid package url type: apk
    at /home/runner/work/_actions/jhutchings1/spdx-to-dependency-graph-action/18b183bb96461852e90574736c3c65812b0f3cd8/webpack:/spdx-to-dependency-graph-action/node_modules/@github/dependency-submission-toolkit/dist/index.js:5317:1
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
>
> /home/runner/work/_actions/jhutchings1/spdx-to-dependency-graph-action/18b183bb96461852e90574736c3c65812b0f3cd8/webpack:/spdx-to-dependency-graph-action/node_modules/@github/dependency-submission-toolkit/dist/index.js:396
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
^
Error: Failed to submit snapshot: HttpError: invalid package url: in manifest '***/fluentd-aggregator@sha256:b5c705b81e919a83fb6f246d6cdeebe4d67771dbcfb7cdac8eb223a849a104df' decoding 'pkg:apk/alpine/tini@0.19.0-r1?arch=x86_64&distro=alpine-3.17.1&upstream=tini': invalid package url type: apk
    at /home/runner/work/_actions/jhutchings1/spdx-to-dependency-graph-action/18b183bb96461852e90574736c3c65812b0f3cd8/webpack:/spdx-to-dependency-graph-action/node_modules/@github/dependency-submission-toolkit/dist/index.js:499:1
    at Generator.throw (<anonymous>)
    at rejected (/home/runner/work/_actions/jhutchings1/spdx-to-dependency-graph-action/18b183bb96461852e90574736c3c65812b0f3cd8/webpack:/spdx-to-dependency-graph-action/node_modules/@github/dependency-submission-toolkit/dist/index.js:396:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Thank you for a very useful action. 👏🏻

**Comment by jhutchings1** [comment]
Thanks for letting me know! I'm following up internally since I think that's a service error.

**Comment by jhutchings1** [comment]
This was a service issue, and the GitHub team has fixed it. Closing
